(function(){
'use strict';
const NS='http://www.w3.org/2000/svg';
function node(svg,name,attrs,text){const n=document.createElementNS(NS,name);Object.keys(attrs||{}).forEach(k=>n.setAttribute(k,attrs[k]));if(text!==undefined)n.textContent=text;svg.appendChild(n);return n;}
function niceTicks(min,max,count){const span=max-min;if(!(span>0))return[min];const raw=span/Math.max(1,count);const p=Math.pow(10,Math.floor(Math.log10(raw)));const q=raw/p;const step=(q<=1?1:q<=2?2:q<=5?5:10)*p;const first=Math.ceil(min/step)*step;const vals=[];for(let v=first;v<=max+step*1e-9;v+=step)vals.push(+v.toFixed(12));return vals;}
function fmt(v){if(Math.abs(v)>=1000||Math.abs(v)>0&&Math.abs(v)<0.01)return Number(v).toExponential(1);const s=(Math.round(v*1000)/1000).toString();return s==='-0'?'0':s;}
function drawAxes(svg,opt){const W=opt.width||850,H=opt.height||470;svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.innerHTML='';const m=Object.assign({left:82,right:28,top:34,bottom:66},opt.margin||{});const L=m.left,R=W-m.right,T=m.top,B=H-m.bottom;const xMin=opt.xMin,xMax=opt.xMax,yMin=opt.yMin,yMax=opt.yMax;const sx=x=>L+(x-xMin)/(xMax-xMin)*(R-L);const sy=y=>B-(y-yMin)/(yMax-yMin)*(B-T);node(svg,'line',{x1:L,y1:B,x2:R,y2:B,stroke:'#53635a','stroke-width':'1.7'});node(svg,'line',{x1:L,y1:T,x2:L,y2:B,stroke:'#53635a','stroke-width':'1.7'});const xt=opt.xTicks||niceTicks(xMin,xMax,opt.xTickCount||6);const yt=opt.yTicks||niceTicks(yMin,yMax,opt.yTickCount||5);xt.forEach(v=>{if(v<xMin-1e-9||v>xMax+1e-9)return;const x=sx(v);node(svg,'line',{x1:x,y1:B,x2:x,y2:B+6,stroke:'#53635a'});node(svg,'text',{x,y:B+23,'text-anchor':'middle','font-size':'12',fill:'#2d3c34'},fmt(v));});yt.forEach(v=>{if(v<yMin-1e-9||v>yMax+1e-9)return;const y=sy(v);node(svg,'line',{x1:L-6,y1:y,x2:L,y2:y,stroke:'#53635a'});node(svg,'text',{x:L-11,y:y+4,'text-anchor':'end','font-size':'12',fill:'#2d3c34'},fmt(v));});if(opt.xLabel)node(svg,'text',{x:(L+R)/2,y:H-18,'text-anchor':'middle','font-size':'14','font-weight':'700',fill:'#26362e'},opt.xLabel);if(opt.yLabel){const yy=(T+B)/2;const t=node(svg,'text',{x:22,y:yy,'text-anchor':'middle','font-size':'14','font-weight':'700',fill:'#26362e'},opt.yLabel);t.setAttribute('transform',`rotate(-90 22 ${yy})`);}return{sx,sy,L,R,T,B,W,H};}
function plotFunction(svg,opt,series){const c=drawAxes(svg,opt);(series||[]).forEach((s,i)=>{const n=s.samples||300,pts=[];for(let j=0;j<=n;j++){const x=opt.xMin+(opt.xMax-opt.xMin)*j/n;let y;try{y=s.fn(x);}catch(e){y=NaN;}if(Number.isFinite(y)&&y>=opt.yMin-(opt.yMax-opt.yMin)*0.02&&y<=opt.yMax+(opt.yMax-opt.yMin)*0.02)pts.push(`${c.sx(x)},${c.sy(y)}`);else if(pts.length){node(svg,'polyline',{points:pts.splice(0).join(' '),fill:'none',stroke:s.color||['#39815e','#a07042','#6f6b9a','#567b74'][i%4],'stroke-width':s.width||2.8,'stroke-linejoin':'round','stroke-linecap':'round','stroke-dasharray':s.dash||''});}}if(pts.length)node(svg,'polyline',{points:pts.join(' '),fill:'none',stroke:s.color||['#39815e','#a07042','#6f6b9a','#567b74'][i%4],'stroke-width':s.width||2.8,'stroke-linejoin':'round','stroke-linecap':'round','stroke-dasharray':s.dash||''});});return c;}
function plotData(svg,opt,series){const c=drawAxes(svg,opt);(series||[]).forEach((s,i)=>{const pts=(s.data||[]).filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1])).map(p=>`${c.sx(p[0])},${c.sy(p[1])}`).join(' ');node(svg,'polyline',{points:pts,fill:'none',stroke:s.color||['#39815e','#a07042','#6f6b9a','#567b74'][i%4],'stroke-width':s.width||2.8,'stroke-linejoin':'round','stroke-linecap':'round','stroke-dasharray':s.dash||''});});return c;}
function label(svg,c,x,y,text,opt){opt=opt||{};node(svg,'text',{x:c.sx(x)+(opt.dx||0),y:c.sy(y)+(opt.dy||0),'text-anchor':opt.anchor||'start','font-size':opt.size||12,fill:opt.fill||'#35423b'},text);}
function point(svg,c,x,y,opt){opt=opt||{};node(svg,'circle',{cx:c.sx(x),cy:c.sy(y),r:opt.r||4.5,fill:opt.fill||'#53635a'});}
function hline(svg,c,y,opt){opt=opt||{};node(svg,'line',{x1:c.L,y1:c.sy(y),x2:c.R,y2:c.sy(y),stroke:opt.stroke||'#aab5af','stroke-width':opt.width||1.3,'stroke-dasharray':opt.dash||'6 5'});}
function vline(svg,c,x,opt){opt=opt||{};node(svg,'line',{x1:c.sx(x),y1:c.T,x2:c.sx(x),y2:c.B,stroke:opt.stroke||'#aab5af','stroke-width':opt.width||1.3,'stroke-dasharray':opt.dash||'6 5'});}
window.MathsBioPlot={plotFunction,plotData,drawAxes,label,point,hline,vline,node};
})();